### ISSUE TITLE
please give us some complete code ode of example

### ISSUE THREAD

**Issue by stickylabdev** [rebus007/WordPressHelper#1]
Please .because we are newbiew and confuse

**Comment by raphaelbussa** [comment]
what you do not understand in examples in the readme?

**Comment by stickylabdev** [comment]
For examplei dont know how to put the link .  evry thing ia hard .and i am always wrong

**Comment by raphaelbussa** [comment]
I think that the examples in the readme are clear. However I will make a sample app

**Comment by stickylabdev** [comment]
Thanks ..iam waiting.

**Comment by stickylabdev** [comment]
Sample .ap please

**Comment by raphaelbussa** [comment]
The sample will be done as soon as possible, so just wait and at the readme explains well how to use the library.

**Comment by stickylabdev** [comment]
Yes .thanks
